name: ci

on:
  push:
    branches:
      - "lab_2"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3.1.0
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_SAIVAKS}}
          password: ${{ secrets.DOCKERHUB_PASS}}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_SAIVAKS }}/test:latest
      - 
        name: Test cl
        uses: ./.github/workflows/cd
        with:
          username: ${{ secrets.MASTER_SLAVE}}
          port: ${{ secrets.OPEN_PORT}}
